#!/bin/bash

GAME_LINES=""

while read -r line; do
  if [[ "$line" == *"InitGame"* ]]; then
    GAME_LINES="$line"
  elif [[ "$line" == *"ShutdownGame"* ]]; then
    echo "$GAME_LINES" | ./$1
    GAME_LINES=""
  else
    GAME_LINES="$GAME_LINES"$'\n'"$line"
  fi
done
