#!/bin/bash

set -euf -o pipefail
FILE="mp_server.log"

go build cod2log_to_json.go structs.go
go build json_to_database.go structs.go

cat $FILE | ./chunk_into cod2log_to_json # | ./json_to_database
